# WordPress конфигурация
# Храните этот файл в безопасности и не коммитьте в репозиторий

wordpress:
  host: "https://www.pnisurov.ru/xmlrpc.php"
  username: ""
  password: ""

vkontakte:
  access_token: ""
  group_id: ""

odnoklassniki:
  access_token: ""
  group_id: ""
  application_key: ""
  application_secret: ""
